- name: generate locale
  command: /usr/sbin/locale-gen {{ locale }}
  register: gen_locale
  changed_when: not "up-to-date" in "{{ gen_locale.stdout_lines }}"

- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  when: gen_locale.changed

- name: create project dirs
  file: path={{ item }} state=directory mode=0777
  with_items: project_folders

- name: create project user
  user: >
    name={{ project_user }}
    password={{ project_user_password }}
    shell=/bin/bash
    group={{ project_user_group }}
    groups=www-data
    append=yes

