- name: create pg Database
  sudo_user: postgres
  postgresql_db: >
      name={{ db_name }}
      encoding=UTF-8

- name: create pg database role
  sudo_user: postgres
  postgresql_user: >
      name={{ db_user }}
      password={{ db_password }}
      db={{ db_name }}
      priv=ALL

