# vim:ft=ansible:

- name: add apt repos
  apt_repository: repo="{{ item }}"
  with_items: apt_repos
  register: add_aptrepos

- name: add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: install system packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: system_packages

- name: install python packages
  pip: name={{ item }}
  with_items: python_packages

- name: ensure latest pip
  pip: name=pip state=latest

- name: install python requirements
  pip: requirements={{ project_python_requirements }} virtualenv={{ virtualenv_path }}
  register: pip_install_requirements

- name: change owner of virtualenvs folder to project user
  file: path=/home/{{ project_user }}/virtualenvs owner={{ project_user }} group={{ project_user_group }} recurse=yes
  when: pip_install_requirements.changed
