---
locale: en_US.UTF-8

project_name: rafee
project_root: "/var/www/{{ project_name }}"
project_path: "/var/www/{{ project_name }}"
project_conf_path: "{{ project_path }}/conf"
project_nginx_conf_path: "{{ project_conf_path }}/nginx"
project_uwsgi_conf_path: "{{ project_conf_path }}/uwsgi"
project_celery_conf_path: "{{ project_conf_path }}/celery"
project_repos_path: "{{ project_path }}/repos"
project_static_path: "{{ project_path }}/static"
project_dist_path: "{{ project_root }}/frontend/dist"

project_user_group: "{{ project_user }}"

project_folders:
    - "{{ project_nginx_conf_path }}"
    - "{{ project_uwsgi_conf_path }}"
    - "{{ project_celery_conf_path }}"
    - "{{ project_repos_path }}"
    - "{{ project_static_path }}"

virtualenv_path: "/home/{{ project_user }}/virtualenvs/{{ project_name }}"

system_packages:
    - build-essential
    - postgresql-9.4
    - postgresql-server-dev-9.4
    - pgadmin3
    - libpq-dev
    - libevent-dev
    - language-pack-en
    - git
    - vim
    - python-pip
    - python-dev
    - redis-server
    - nginx

python_packages:
    - pip
    - virtualenv
    - psycopg2

django_superuser_username: admin

db_distro: utopic
db_name: "{{ project_name }}_db"
db_user: "{{ project_user }}"
db_password: "{{ project_user_password }}"

supervisor_config_file: /etc/supervisord.conf
supervisor_ctl_path: "{{ virtualenv_path }}/bin/supervisorctl"
supervisor_socket_file: /var/run/supervisor.sock

nginx_disable_assets_caching: false
nginx_config_file: "{{ project_nginx_conf_path }}/{{ project_name }}.conf"
nginx_server_port: 8000
nginx_server_name: localhost
nginx_socket_file: "/var/run/{{ project_name }}_nginx.sock"

uwsgi_touch_reload: "{{ project_root }}/.reload"
uwsgi_params_file: "{{ project_uwsgi_conf_path }}/uwsgi_params"
uwsgi_ini_file: "{{ project_uwsgi_conf_path }}/uwsgi.ini"
