- name: create celery log dir
  file: path=/var/log/celery state=directory

- name: start celery
  supervisorctl: name=celery state=started supervisorctl_path={{ supervisor_ctl_path }}

- name: start celerybeat
  supervisorctl: name=celerybeat state=started supervisorctl_path={{ supervisor_ctl_path }}

